@echo off
setlocal

set "KernelKey=HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\Kernel"
reg add "%KernelKey%" /v AdjustDpcThreshold /t REG_DWORD /d 10 /f
reg add "%KernelKey%" /v AlwaysTrackIoBoosting /t REG_DWORD /d 0 /f
reg add "%KernelKey%" /v AmdTprLowerInterruptDelayConfig /t REG_DWORD /d 0 /f
reg add "%KernelKey%" /v BoostingPeriodMultiplier /t REG_DWORD /d 3 /f
reg add "%KernelKey%" /v BugCheckUnexpectedInterrupts /t REG_DWORD /d 0 /f
reg add "%KernelKey%" /v CacheAwareScheduling /t REG_DWORD /d 47 /f
reg add "%KernelKey%" /v CacheErrataOverride /t REG_DWORD /d 0 /f
reg add "%KernelKey%" /v CacheIsoBitmap /t REG_DWORD /d 0 /f
reg add "%KernelKey%" /v DebuggerIsStallOwner /t REG_DWORD /d 0 /f
reg add "%KernelKey%" /v DebugPollInterval /t REG_DWORD /d 2000 /f
reg add "%KernelKey%" /v DefaultDynamicHeteroCpuPolicy /t REG_DWORD /d 3 /f
reg add "%KernelKey%" /v DefaultHeteroCpuPolicy /t REG_DWORD /d 5 /f
reg add "%KernelKey%" /v DeviceOwnerProtectionDowngradeAllowed /t REG_DWORD /d 0 /f
reg add "%KernelKey%" /v DisableControlFlowGuardExportSuppression /t REG_DWORD /d 0 /f
reg add "%KernelKey%" /v DisableExceptionChainValidation /t REG_DWORD /d 2 /f
reg add "%KernelKey%" /v DisableLightWeightSuspend /t REG_DWORD /d 0 /f
reg add "%KernelKey%" /v DisableLowQosTimerResolution /t REG_DWORD /d 1 /f
reg add "%KernelKey%" /v DisablePointerParameterAlignmentValidation /t REG_DWORD /d 0 /f
reg add "%KernelKey%" /v DisableTsx /t REG_DWORD /d 0 /f
reg add "%KernelKey%" /v DpcCumulativeSoftTimeout /t REG_DWORD /d 120000 /f
reg add "%KernelKey%" /v DpcQueueDepth /t REG_DWORD /d 1 /f
reg add "%KernelKey%" /v DpcSoftTimeout /t REG_DWORD /d 20000 /f
reg add "%KernelKey%" /v DPCTimeout /t REG_DWORD /d 20000 /f
reg add "%KernelKey%" /v DpcWatchdogPeriod /t REG_DWORD /d 120000 /f
reg add "%KernelKey%" /v DpcWatchdogProfileBufferSizeBytes /t REG_DWORD /d 266240 /f
reg add "%KernelKey%" /v DpcWatchdogProfileCumulativeDpcThreshold /t REG_DWORD /d 110000 /f
reg add "%KernelKey%" /v DpcWatchdogProfileOffset /t REG_DWORD /d 10000 /f
reg add "%KernelKey%" /v DpcWatchdogProfileSingleDpcThreshold /t REG_DWORD /d 18333 /f
reg add "%KernelKey%" /v DriveRemappingMitigation /t REG_DWORD /d 1 /f
reg add "%KernelKey%" /v DynamicHeteroCpuPolicyExpectedRuntime /t REG_DWORD /d 5200 /f
reg add "%KernelKey%" /v DynamicHeteroCpuPolicyImportant /t REG_DWORD /d 2 /f
reg add "%KernelKey%" /v DynamicHeteroCpuPolicyImportantPriority /t REG_DWORD /d 8 /f
reg add "%KernelKey%" /v DynamicHeteroCpuPolicyImportantShort /t REG_DWORD /d 3 /f
reg add "%KernelKey%" /v DynamicHeteroCpuPolicyMask /t REG_DWORD /d 7 /f
reg add "%KernelKey%" /v EnablePerCpuClockTickScheduling /t REG_DWORD /d 0 /f
reg add "%KernelKey%" /v EnableTickAccumulationFromAccountingPeriods /t REG_DWORD /d 0 /f
reg add "%KernelKey%" /v EnableWerUserReporting /t REG_DWORD /d 1 /f
reg add "%KernelKey%" /v ForceBugcheckForDpcWatchdog /t REG_DWORD /d 0 /f
reg add "%KernelKey%" /v ForceForegroundBoostDecay /t REG_DWORD /d 0 /f
reg add "%KernelKey%" /v ForceIdleGracePeriod /t REG_DWORD /d 5 /f
reg add "%KernelKey%" /v ForceParkingRequested /t REG_DWORD /d 1 /f
reg add "%KernelKey%" /v GlobalTimerResolutionRequests /t REG_DWORD /d 0 /f
reg add "%KernelKey%" /v HeteroFavoredCoreFallback /t REG_DWORD /d 0 /f
reg add "%KernelKey%" /v HeteroSchedulerOptions /t REG_DWORD /d 0 /f
reg add "%KernelKey%" /v HeteroSchedulerOptionsMask /t REG_DWORD /d 0 /f
reg add "%KernelKey%" /v HgsPlusFeedbackUpdateThresholdNetRuntime /t REG_DWORD /d 20 /f
reg add "%KernelKey%" /v HgsPlusFeedbackUpdateThresholdRuntime /t REG_DWORD /d 20 /f
reg add "%KernelKey%" /v HgsPlusHigherPerfClassFeedbackThreshold /t REG_DWORD /d 1 /f
reg add "%KernelKey%" /v HgsPlusInvalidFeedbackDefaultClass /t REG_DWORD /d 0 /f
reg add "%KernelKey%" /v HgsPlusInvalidFeedbackDefaultClassSet /t REG_DWORD /d 0 /f
reg add "%KernelKey%" /v HgsPlusInvalidFeedbackLimit /t REG_DWORD /d 50 /f
reg add "%KernelKey%" /v HgsPlusLowerPerfClassFeedbackThreshold /t REG_DWORD /d 4 /f
reg add "%KernelKey%" /v HgsPlusMinimumScoreDifferenceForSwap /t REG_DWORD /d 25 /f
reg add "%KernelKey%" /v HgsPlusThreadCreationDefaultClass /t REG_DWORD /d 0 /f
reg add "%KernelKey%" /v HotpatchTestMode /t REG_DWORD /d 0 /f
reg add "%KernelKey%" /v HyperStartDisabled /t REG_DWORD /d 0 /f
reg add "%KernelKey%" /v IdealDpcRate /t REG_DWORD /d 40 /f
reg add "%KernelKey%" /v IdealNodeRandomized /t REG_DWORD /d 1 /f
reg add "%KernelKey%" /v InterruptSteeringFlags /t REG_DWORD /d 0 /f
reg add "%KernelKey%" /v LongDpcQueueThreshold /t REG_DWORD /d 3 /f
reg add "%KernelKey%" /v LongDpcRuntimeThreshold /t REG_DWORD /d 100 /f
reg add "%KernelKey%" /v MaxDynamicTickDuration /t REG_DWORD /d 8 /f
reg add "%KernelKey%" /v MaximumCooperativeIdleSearchWidth /t REG_DWORD /d 16 /f
reg add "%KernelKey%" /v MaximumSharedReadyQueueSize /t REG_DWORD /d 260 /f
reg add "%KernelKey%" /v MinimumDpcRate /t REG_DWORD /d 3 /f
reg add "%KernelKey%" /v MitigationAuditOptions /t REG_DWORD /d 0 /f
reg add "%KernelKey%" /v MitigationOptions /t REG_DWORD /d 0 /f
reg add "%KernelKey%" /v ObCaseInsensitive /t REG_DWORD /d 1 /f
reg add "%KernelKey%" /v ObObjectSecurityInheritance /t REG_DWORD /d 0 /f
reg add "%KernelKey%" /v ObTracePermanent /t REG_DWORD /d 0 /f
reg add "%KernelKey%" /v ObTracePoolTags /t REG_DWORD /d 0 /f
reg add "%KernelKey%" /v ObTraceProcessName /t REG_DWORD /d 0 /f
reg add "%KernelKey%" /v ObUnsecureGlobalNames /t REG_DWORD /d 6619246 /f
reg add "%KernelKey%" /v PassiveWatchdogTimeout /t REG_DWORD /d 300 /f
reg add "%KernelKey%" /v PerfIsoEnabled /t REG_DWORD /d 0 /f
reg add "%KernelKey%" /v PoCleanShutdownFlags /t REG_DWORD /d 0 /f
reg add "%KernelKey%" /v PowerOffFrozenProcessors /t REG_DWORD /d 0 /f
reg add "%KernelKey%" /v ReadyTimeTicks /t REG_DWORD /d 6 /f
reg add "%KernelKey%" /v RebalanceMinPriority /t REG_DWORD /d 1 /f
reg add "%KernelKey%" /v ReservedCpuSets /t REG_DWORD /d 0 /f
reg add "%KernelKey%" /v ScanLatencyTicks /t REG_DWORD /d 7 /f
reg add "%KernelKey%" /v SeAllowAllApplicationAceRemoval /t REG_DWORD /d 0 /f
reg add "%KernelKey%" /v SeAllowSessionImpersonationCapability /t REG_DWORD /d 0 /f
reg add "%KernelKey%" /v SeCompatFlags /t REG_DWORD /d 0 /f
reg add "%KernelKey%" /v SeLpacEnableWatsonReporting /t REG_DWORD /d 0 /f
reg add "%KernelKey%" /v SeLpacEnableWatsonThrottling /t REG_DWORD /d 1 /f
reg add "%KernelKey%" /v SerializeTimerExpiration /t REG_DWORD /d 0 /f
reg add "%KernelKey%" /v SeTokenDoesNotTrackSessionObject /t REG_DWORD /d 0 /f
reg add "%KernelKey%" /v SeTokenLeakDiag /t REG_DWORD /d 0 /f
reg add "%KernelKey%" /v SeTokenSingletonAttributesConfig /t REG_DWORD /d 3 /f
reg add "%KernelKey%" /v SplitLargeCaches /t REG_DWORD /d 0 /f
reg add "%KernelKey%" /v ThreadDpcEnable /t REG_DWORD /d 0 /f
reg add "%KernelKey%" /v ThreadReadyCount /t REG_DWORD /d 1 /f
reg add "%KernelKey%" /v TimerCheckFlags /t REG_DWORD /d 1 /f
reg add "%KernelKey%" /v VerifierDpcScalingFactor /t REG_DWORD /d 1 /f
reg add "%KernelKey%" /v VirtualHeteroHysteresis /t REG_DWORD /d 4294967295 /f
reg add "%KernelKey%" /v VpThreadSystemWorkPriority /t REG_DWORD /d 30 /f
reg add "%KernelKey%" /v WpsSimulationOverride /t REG_DWORD /d 0 /f
reg add "%KernelKey%" /v XStateContextLookasidePerProcMaxDepth /t REG_DWORD /d 0 /f
set "RngKey=%KernelKey%\RNG"
reg add "%RngKey%" /v RNGAuxiliarySeed /t REG_DWORD /d 742978275 /f
set "GfxKey=HKLM\SYSTEM\CurrentControlSet\Control\GraphicsDrivers"
reg add "%GfxKey%" /v MiracastUseIhvDriver /t REG_DWORD /d 2 /f
reg add "%GfxKey%" /v MiracastForceDisable /t REG_DWORD /d 2 /f
reg add "%GfxKey%" /v MiracastDisabled /t REG_DWORD /d 1 /f
reg add "%GfxKey%" /v ContextNoPatchMode /t REG_DWORD /d 0 /f
reg add "%GfxKey%" /v CreateGdiPrimaryOnSlaveGpu /t REG_DWORD /d 0 /f
reg add "%GfxKey%" /v CrtcPhaseFrames /t REG_DWORD /d 2 /f
reg add "%GfxKey%" /v DeadlockPulse /t REG_DWORD /d 5000 /f
reg add "%GfxKey%" /v DeadlockPulseTolerance /t REG_DWORD /d 500 /f
reg add "%GfxKey%" /v DeadlockTimeout /t REG_DWORD /d 30000 /f
reg add "%GfxKey%" /v DisableBadDriverCheckForHwProtection /t REG_DWORD /d 0 /f
reg add "%GfxKey%" /v DisableBoostedVSyncVirtualization /t REG_DWORD /d 0 /f
reg add "%GfxKey%" /v DisableGdiContextGpuVa /t REG_DWORD /d 0 /f
reg add "%GfxKey%" /v DisableIndependentVidPnVSync /t REG_DWORD /d 0 /f
reg add "%GfxKey%" /v DisableMonitoredFenceGpuVa /t REG_DWORD /d 0 /f
reg add "%GfxKey%" /v DisableMultiSourceMPOCheck /t REG_DWORD /d 0 /f
reg add "%GfxKey%" /v DisableOverlays /t REG_DWORD /d 0 /f
reg add "%GfxKey%" /v DisablePagingContextGpuVa /t REG_DWORD /d 0 /f
reg add "%GfxKey%" /v DisableSecondaryIFlipSupport /t REG_DWORD /d 0 /f
reg add "%GfxKey%" /v DriverManagesResidencyOverride /t REG_DWORD /d 1 /f
reg add "%GfxKey%" /v DriverStoreCopyMode /t REG_DWORD /d 1 /f
reg add "%GfxKey%" /v EnableBasicRenderGpuPv /t REG_DWORD /d 0 /f
reg add "%GfxKey%" /v EnableDecodeMPO /t REG_DWORD /d 1 /f
reg add "%GfxKey%" /v EnableFbrValidation /t REG_DWORD /d 1 /f
reg add "%GfxKey%" /v EnableMultiPlaneOverlay3DDIs /t REG_DWORD /d 0 /f
reg add "%GfxKey%" /v EnableOfferReclaimOnDriver /t REG_DWORD /d 1 /f
reg add "%GfxKey%" /v EnablePanelFitterSupport /t REG_DWORD /d 0 /f
reg add "%GfxKey%" /v EnableTimedCalls /t REG_DWORD /d 0 /f
reg add "%GfxKey%" /v EnableWDDM23Synchronization /t REG_DWORD /d 0 /f
reg add "%GfxKey%" /v Force32BitFences /t REG_DWORD /d 0 /f
reg add "%GfxKey%" /v ForceDirectFlip /t REG_DWORD /d 0 /f
reg add "%GfxKey%" /v ForceEnableDxgMms2 /t REG_DWORD /d 0 /f
reg add "%GfxKey%" /v ForceExplicitResidencyNotification /t REG_DWORD /d 0 /f
reg add "%GfxKey%" /v ForceInitPagingProcessVaSpace /t REG_DWORD /d 0 /f
reg add "%GfxKey%" /v ForceReplicateGdiContent /t REG_DWORD /d 0 /f
reg add "%GfxKey%" /v ForceSecondaryIFlipSupport /t REG_DWORD /d 0 /f
reg add "%GfxKey%" /v ForceSecondaryMPOSupport /t REG_DWORD /d 0 /f
reg add "%GfxKey%" /v ForceSurpriseRemovalSupport /t REG_DWORD /d 0 /f
reg add "%GfxKey%" /v ForceVariableRefresh /t REG_DWORD /d 0 /f
reg add "%GfxKey%" /v GdiPhysicalAdapterIndex /t REG_DWORD /d 0 /f
reg add "%GfxKey%" /v GpuPriorityChangeMode /t REG_DWORD /d 1 /f
reg add "%GfxKey%" /v HighPriorityCompletionMode /t REG_DWORD /d 1 /f
reg add "%GfxKey%" /v InitialPagingQueueFenceValue /t REG_DWORD /d 7000 /f
reg add "%GfxKey%" /v IoMmuFlags /t REG_DWORD /d 0 /f
reg add "%GfxKey%" /v KnownProcessBoostMode /t REG_DWORD /d 1 /f
reg add "%GfxKey%" /v LeanMemoryLimit /t REG_DWORD /d 1395864371 /f
reg add "%GfxKey%" /v LeanMemoryLimitHigh /t REG_DWORD /d 16 /f
reg add "%GfxKey%" /v NumVirtualFunctions /t REG_DWORD /d 0 /f
reg add "%GfxKey%" /v SmallQuantumMode /t REG_DWORD /d 1 /f
reg add "%GfxKey%" /v DefaultActiveIdleThreshold /t REG_DWORD /d 2000 /f
reg add "%GfxKey%" /v DefaultD3TransitionIdleLongTimeThreshold /t REG_DWORD /d 60000 /f
reg add "%GfxKey%" /v DefaultD3TransitionIdleShortTimeThreshold /t REG_DWORD /d 10000 /f
reg add "%GfxKey%" /v DefaultD3TransitionIdleVeryLongTimeThreshold /t REG_DWORD /d 60000 /f
reg add "%GfxKey%" /v DefaultD3TransitionLatencyActivelyUsed /t REG_DWORD /d 10 /f
reg add "%GfxKey%" /v DefaultD3TransitionLatencyIdleLongTime /t REG_DWORD /d 140000 /f
reg add "%GfxKey%" /v DefaultD3TransitionLatencyIdleMonitorOff /t REG_DWORD /d 250000 /f
reg add "%GfxKey%" /v DefaultD3TransitionLatencyIdleNoContext /t REG_DWORD /d 250000 /f
reg add "%GfxKey%" /v DefaultD3TransitionLatencyIdleShortTime /t REG_DWORD /d 100000 /f
reg add "%GfxKey%" /v DefaultD3TransitionLatencyIdleVeryLongTime /t REG_DWORD /d 200000 /f
reg add "%GfxKey%" /v DefaultExpectedResidency /t REG_DWORD /d 2000 /f
reg add "%GfxKey%" /v DefaultIdleThresholdIdle0 /t REG_DWORD /d 200 /f
reg add "%GfxKey%" /v DefaultIdleThresholdIdle0MonitorOff /t REG_DWORD /d 100 /f
reg add "%GfxKey%" /v DefaultLatencyToleranceIdle0 /t REG_DWORD /d 80 /f
reg add "%GfxKey%" /v DefaultLatencyToleranceIdle0MonitorOff /t REG_DWORD /d 2000 /f
reg add "%GfxKey%" /v DefaultLatencyToleranceIdle1 /t REG_DWORD /d 15000 /f
reg add "%GfxKey%" /v DefaultLatencyToleranceIdle1MonitorOff /t REG_DWORD /d 50000 /f
reg add "%GfxKey%" /v DefaultLatencyToleranceMemory /t REG_DWORD /d 15000 /f
reg add "%GfxKey%" /v DefaultLatencyToleranceMemoryNoContext /t REG_DWORD /d 30000 /f
reg add "%GfxKey%" /v DefaultLatencyToleranceNoContext /t REG_DWORD /d 35000 /f
reg add "%GfxKey%" /v DefaultLatencyToleranceNoContextMonitorOff /t REG_DWORD /d 100000 /f
reg add "%GfxKey%" /v DefaultLatencyToleranceOther /t REG_DWORD /d 4294967295 /f
reg add "%GfxKey%" /v DefaultLatencyToleranceTimerPeriod /t REG_DWORD /d 200 /f
reg add "%GfxKey%" /v DefaultMemoryRefreshLatencyToleranceActivelyUsed /t REG_DWORD /d 80 /f
reg add "%GfxKey%" /v DefaultMemoryRefreshLatencyToleranceIdleShortTime /t REG_DWORD /d 15000 /f
reg add "%GfxKey%" /v DefaultMemoryRefreshLatencyToleranceMonitorOff /t REG_DWORD /d 80000 /f
reg add "%GfxKey%" /v DefaultMemoryRefreshLatencyToleranceNoContext /t REG_DWORD /d 30000 /f
reg add "%GfxKey%" /v DefaultPowerNotRequiredTimeout /t REG_DWORD /d 25000 /f
reg add "%GfxKey%" /v DisableDevicePowerRequired /t REG_DWORD /d 0 /f
reg add "%GfxKey%" /v DisablePStateManagement /t REG_DWORD /d 0 /f
reg add "%GfxKey%" /v EnablePODebounce /t REG_DWORD /d 0 /f
reg add "%GfxKey%" /v EnableRuntimePowerManagement /t REG_DWORD /d 1 /f
reg add "%GfxKey%" /v lowdebounce /t REG_DWORD /d 3 /f
reg add "%GfxKey%" /v MonitorLatencyTolerance /t REG_DWORD /d 1000 /f
reg add "%GfxKey%" /v MonitorRefreshLatencyTolerance /t REG_DWORD /d 17000 /f
reg add "%GfxKey%" /v uglitch /t REG_DWORD /d 900 /f
reg add "%GfxKey%" /v uhigh /t REG_DWORD /d 700 /f
reg add "%GfxKey%" /v uideal /t REG_DWORD /d 500 /f
reg add "%GfxKey%" /v ulow /t REG_DWORD /d 300 /f
reg add "%GfxKey%" /v AllowAdvancedEtwLogging /t REG_DWORD /d 0 /f
reg add "%GfxKey%" /v DiagnosticsBufferExpansionTime /t REG_DWORD /d 300 /f
reg add "%GfxKey%" /v EnableFuzzing /t REG_DWORD /d 0 /f
reg add "%GfxKey%" /v EnableHMDTestMode /t REG_DWORD /d 0 /f
reg add "%GfxKey%" /v EnableIgnoreWin32ProcessStatus /t REG_DWORD /d 0 /f
reg add "%GfxKey%" /v ExternalDiagnosticsBufferMultiplier /t REG_DWORD /d 1 /f
reg add "%GfxKey%" /v ExternalDiagnosticsBufferSize /t REG_DWORD /d 16384 /f
reg add "%GfxKey%" /v ForceUsb4MonitorSupport /t REG_DWORD /d 0 /f
reg add "%GfxKey%" /v InternalDiagnosticsBufferMultiplier /t REG_DWORD /d 2 /f
reg add "%GfxKey%" /v InternalDiagnosticsBufferSize /t REG_DWORD /d 65536 /f
reg add "%GfxKey%" /v InvestigationDebugParameter /t REG_DWORD /d 0 /f
reg add "%GfxKey%" /v MaximumAdapterCount /t REG_DWORD /d 32 /f
reg add "%GfxKey%" /v NodeUsageTelemetryTimerInterval /t REG_DWORD /d 0 /f
reg add "%GfxKey%" /v PreserveFirmwareMode /t REG_DWORD /d 0 /f
reg add "%GfxKey%" /v PreventFullscreenWireFormatChange /t REG_DWORD /d 0 /f
reg add "%GfxKey%" /v RapidHpdMaxChainInMilliseconds /t REG_DWORD /d 0 /f
reg add "%GfxKey%" /v RapidHpdTimeoutInMilliseconds /t REG_DWORD /d 0 /f
reg add "%GfxKey%" /v TerminationListSizeLimit /t REG_DWORD /d 67108864 /f
reg add "%GfxKey%" /v TreatUsb4MonitorAsNormal /t REG_DWORD /d 0 /f
reg add "%GfxKey%" /v Usb4MonitorDpcdDP_IN_Adapter_Number /t REG_DWORD /d 0 /f
reg add "%GfxKey%" /v Usb4MonitorDpcdUSB4_Driver_ID /t REG_DWORD /d 0 /f
reg add "%GfxKey%" /v Usb4MonitorPowerOnDelayInSeconds /t REG_DWORD /d 0 /f
reg add "%GfxKey%" /v Usb4MonitorTargetId /t REG_DWORD /d 0 /f
reg add "%GfxKey%" /v ValidateWDDMCaps /t REG_DWORD /d 0 /f
reg add "%GfxKey%" /v WDDM2LockManagement /t REG_DWORD /d 1 /f
reg add "%GfxKey%" /v DisableVaBackedVm /t REG_DWORD /d 0 /f
reg add "%GfxKey%" /v DisableVersionMismatchCheck /t REG_DWORD /d 0 /f
reg add "%GfxKey%" /v GpuVirtualizationFlags /t REG_DWORD /d 0 /f
reg add "%GfxKey%" /v LimitNumberOfVfs /t REG_DWORD /d 0 /f
reg add "%GfxKey%" /v VirtualGpuOnly /t REG_DWORD /d 0 /f
reg add "%GfxKey%" /v ForceBddFallbackOnly /t REG_DWORD /d 0 /f
reg add "%GfxKey%" /v HwSchMode /t REG_DWORD /d 2 /f
reg add "%GfxKey%" /v HwSchOverrideBlockList /t REG_DWORD /d 1 /f
reg add "%GfxKey%" /v HwSchTreatExperimentalAsStable /t REG_DWORD /d 0 /f
reg add "%GfxKey%" /v MiracastDefaultRtspPort /t REG_DWORD /d 7236 /f
reg add "%GfxKey%" /v PlatformSupportMiracast /t REG_DWORD /d 0 /f
reg add "%GfxKey%" /v SupportMultipleIntegratedDisplays /t REG_DWORD /d 0 /f
reg add "%GfxKey%" /v SuspendAdapterTimerPeriod /t REG_DWORD /d 500000 /f
reg add "%GfxKey%" /v EnableExperimentalRefreshRates /t REG_DWORD /d 0 /f
reg add "%GfxKey%" /v RapidHPDThresholdCount /t REG_DWORD /d 5 /f
reg add "%GfxKey%" /v RapidHPDTime /t REG_DWORD /d 1000 /f
reg add "%GfxKey%" /v TdrDdiDelay /t REG_DWORD /d 5 /f
reg add "%GfxKey%" /v TdrDebugMode /t REG_DWORD /d 2 /f
reg add "%GfxKey%" /v TdrDelay /t REG_DWORD /d 2 /f
reg add "%GfxKey%" /v TdrDodPresentDelay /t REG_DWORD /d 2 /f
reg add "%GfxKey%" /v TdrDodVSyncDelay /t REG_DWORD /d 2 /f
reg add "%GfxKey%" /v TdrLevel /t REG_DWORD /d 3 /f
reg add "%GfxKey%" /v TdrLimitCount /t REG_DWORD /d 5 /f
reg add "%GfxKey%" /v TdrLimitTime /t REG_DWORD /d 60 /f
reg add "%GfxKey%" /v DRTTestEnable /t REG_DWORD /d 0 /f
reg add "%GfxKey%" /v EnableAcmSupportDeveloperPreview /t REG_DWORD /d 0 /f
reg add "%GfxKey%" /v ForceEnableDWMClone /t REG_DWORD /d 0 /f
reg add "%GfxKey%" /v HybridInternalPanelOverrideEnable /t REG_DWORD /d 0 /f
reg add "%GfxKey%" /v IsInternalRelease /t REG_DWORD /d 0 /f
reg add "%GfxKey%" /v MultiMonSupport /t REG_DWORD /d 1 /f
reg add "%GfxKey%" /v OutputDuplicationSessionApplicationLimit /t REG_DWORD /d 4 /f
reg add "%GfxKey%" /v TdrTestMode /t REG_DWORD /d 0 /f
reg add "%GfxKey%" /v UnsupportedMonitorModesAllowed /t REG_DWORD /d 0 /f
:: Additional GPU scheduling optimizations
reg add "%GfxKey%\Scheduler" /v EnablePreemption /t REG_DWORD /d 0 /f
reg add "%GfxKey%" /v PerfLevelSrc /t REG_DWORD /d 3738 /f
reg add "%GfxKey%" /v PowerMizerEnable /t REG_DWORD /d 1 /f
reg add "%GfxKey%" /v PowerMizerLevel /t REG_DWORD /d 1 /f
reg add "%GfxKey%" /v PowerMizerLevelAC /t REG_DWORD /d 1 /f
set "GfxPowerKey=%GfxKey%\Power"
reg add "%GfxPowerKey%" /v UseSelfRefreshVRAMInS3 /t REG_DWORD /d 1 /f
set "GfxBasicKey=%GfxKey%\BasicDisplay"
reg add "%GfxBasicKey%" /v BasicDisplayUserNotified /t REG_DWORD /d 0 /f
reg add "%GfxBasicKey%" /v DisableBasicDisplayFallback /t REG_DWORD /d 4294967295 /f
reg add "%GfxBasicKey%" /v EnableBasicDisplayFallback /t REG_DWORD /d 4294967295 /f
reg add "%GfxBasicKey%" /v ForcePreserveBootDisplay /t REG_DWORD /d 0 /f
set "GfxSmmKey=%GfxKey%\Smm"
reg add "%GfxSmmKey%" /v DebugMode /t REG_DWORD /d 0 /f
reg add "%GfxSmmKey%" /v EnablePageTracking /t REG_DWORD /d 0 /f
reg add "%GfxSmmKey%" /v ForceDmaRemapping /t REG_DWORD /d 0 /f
reg add "%GfxSmmKey%" /v ForceEnableIommu /t REG_DWORD /d 0 /f
reg add "%GfxSmmKey%" /v IdentityMappedPassthrough /t REG_DWORD /d 0 /f
reg add "%GfxSmmKey%" /v LogicalAddressMode /t REG_DWORD /d 0 /f
reg add "%GfxSmmKey%" /v PreferHighLogicalAddresses /t REG_DWORD /d 0 /f
set "GfxDmmKey=%GfxKey%\DMM"
reg add "%GfxDmmKey%" /v AssertOnDdiViolation /t REG_DWORD /d 0 /f
reg add "%GfxDmmKey%" /v BadMonitorModeDiag /t REG_DWORD /d 2 /f
reg add "%GfxDmmKey%" /v EnableVirtualRefreshRateOnExternalMonitor /t REG_DWORD /d 0 /f
reg add "%GfxDmmKey%" /v HPDFilterLimit /t REG_DWORD /d 20000000 /f
reg add "%GfxDmmKey%" /v LongLinkTrainingTimeout /t REG_DWORD /d 1000 /f
reg add "%GfxDmmKey%" /v ModeListCaching /t REG_DWORD /d 1 /f
reg add "%GfxDmmKey%" /v SetTimingsFlags /t REG_DWORD /d 0 /f
reg add "%GfxDmmKey%" /v ShortLinkTrainingTimeout /t REG_DWORD /d 200 /f
set "GfxValidationKey=%GfxKey%\Validation"
reg add "%GfxValidationKey%" /v FailEscapeDDI /t REG_DWORD /d 0 /f
reg add "%GfxValidationKey%" /v FailRenderDDI /t REG_DWORD /d 0 /f
reg add "%GfxValidationKey%" /v FailReserveGPUVA /t REG_DWORD /d 0 /f
reg add "%GfxValidationKey%" /v Level /t REG_DWORD /d 0 /f
reg add "%GfxValidationKey%" /v ReportVirtualMachine /t REG_DWORD /d 0 /f
set "GfxMonitorKey=%GfxKey%\MonitorDataStore\MONITOR-ID"
reg add "%GfxMonitorKey%" /v AdvancedColorEnabled /t REG_DWORD /d 0 /f
reg add "%GfxMonitorKey%" /v AutoColorManagementEnabled /t REG_DWORD /d 0 /f
reg add "%GfxMonitorKey%" /v EnableIntegratedPanelAcmByDefault /t REG_DWORD /d 0 /f
reg add "%GfxMonitorKey%" /v EnableIntegratedPanelHdrByDefault /t REG_DWORD /d 0 /f
reg add "%GfxMonitorKey%" /v HDREnabled /t REG_DWORD /d 0 /f
reg add "%GfxMonitorKey%" /v MicrosoftApprovedAcmSupport /t REG_DWORD /d 0 /f
:: Device-specific DxgkSettings placeholder
set "PnPKey=<PnPDeviceKey>"
reg add "%PnPKey%\DxgkSettings" /v UseSelfRefreshVRAMInS3 /t REG_DWORD /d 1 /f
reg add "%PnPKey%" /v EnableVirtualTopologySupport /t REG_DWORD /d 0 /f
reg add "%PnPKey%" /v NeedToSuspendVidSchBeforeSetGammaRamp /t REG_DWORD /d 1 /f
reg add "%PnPKey%" /v DisableNonPOSTDevice /t REG_DWORD /d 0 /f
reg add "%PnPKey%" /v ACGSupported /t REG_DWORD /d 0 /f
reg add "%PnPKey%" /v DxgkGpuVaIommuRequired /t REG_DWORD /d 0 /f
reg add "%PnPKey%" /v DxgkGpuVaIommuGlobalSupported /t REG_DWORD /d 0 /f
reg add "%PnPKey%" /v AllowUnspecifiedVSync /t REG_DWORD /d 0 /f
reg add "%PnPKey%" /v AllowUnspecifiedHSync /t REG_DWORD /d 0 /f
reg add "%PnPKey%" /v AllowUnspecifiedPixelRate /t REG_DWORD /d 0 /f
reg add "%PnPKey%" /v ForceDualViewBehavior /t REG_DWORD /d 0 /f
set "DwmKey=HKLM\SOFTWARE\Microsoft\Windows\Dwm"
reg add "%DwmKey%" /v BlackOutAllReadback /t REG_DWORD /d 0 /f
reg add "%DwmKey%" /v ConfigureInput /t REG_DWORD /d 0 /f
reg add "%DwmKey%" /v CpuClipAASinkEnableIntermediates /t REG_DWORD /d 1 /f
reg add "%DwmKey%" /v CpuClipAASinkEnableOcclusion /t REG_DWORD /d 1 /f
reg add "%DwmKey%" /v CpuClipAASinkEnableRender /t REG_DWORD /d 1 /f
reg add "%DwmKey%" /v CpuClipAreaThreshold /t REG_DWORD /d 20000 /f
reg add "%DwmKey%" /v CpuClipWarpPartitionThreshold /t REG_DWORD /d 1024 /f
reg add "%DwmKey%" /v DisableDrawListCaching /t REG_DWORD /d 0 /f
reg add "%DwmKey%" /v DisableProjectedShadows /t REG_DWORD /d 1 /f
reg add "%DwmKey%" /v DisplayChangeTimeoutMs /t REG_DWORD /d 1000 /f
reg add "%DwmKey%" /v EnableBackdropBlurCaching /t REG_DWORD /d 1 /f
reg add "%DwmKey%" /v EnableCommonSuperSets /t REG_DWORD /d 1 /f
reg add "%DwmKey%" /v EnableCpuClipping /t REG_DWORD /d 1 /f
reg add "%DwmKey%" /v EnableDDisplayScanoutCaching /t REG_DWORD /d 1 /f
reg add "%DwmKey%" /v EnableEffectCaching /t REG_DWORD /d 1 /f
reg add "%DwmKey%" /v EnableFrontBufferRenderChecks /t REG_DWORD /d 1 /f
reg add "%DwmKey%" /v EnableMegaRects /t REG_DWORD /d 1 /f
reg add "%DwmKey%" /v EnablePrimitiveReordering /t REG_DWORD /d 1 /f
reg add "%DwmKey%" /v ForceFullDirtyRendering /t REG_DWORD /d 0 /f
reg add "%DwmKey%" /v GammaBlendPencil /t REG_DWORD /d 1 /f
reg add "%DwmKey%" /v GammaBlendWithFP16 /t REG_DWORD /d 1 /f
reg add "%DwmKey%" /v InkGPUAccelOverrideVendorWhitelist /t REG_DWORD /d 0 /f
reg add "%DwmKey%" /v LayerClippingMode /t REG_DWORD /d 2 /f
reg add "%DwmKey%" /v LogExpressionPerfStats /t REG_DWORD /d 0 /f
reg add "%DwmKey%" /v MajorityScreenTest_MinArea /t REG_DWORD /d 80 /f
reg add "%DwmKey%" /v MajorityScreenTest_MinLength /t REG_DWORD /d 80 /f
reg add "%DwmKey%" /v MaxD3DFeatureLevel /t REG_DWORD /d 0 /f
reg add "%DwmKey%" /v MegaRectSearchCount /t REG_DWORD /d 100 /f
reg add "%DwmKey%" /v MegaRectSize /t REG_DWORD /d 100000 /f
reg add "%DwmKey%" /v MousewheelAnimationDurationMs /t REG_DWORD /d 250 /f
reg add "%DwmKey%" /v MousewheelScrollingMode /t REG_DWORD /d 0 /f
reg add "%DwmKey%" /v OptimizeForDirtyExpressions /t REG_DWORD /d 1 /f
reg add "%DwmKey%" /v OverlayMinFPS /t REG_DWORD /d 30 /f
reg add "%DwmKey%" /v RenderThreadTimeoutMilliseconds /t REG_DWORD /d 5000 /f
reg add "%DwmKey%" /v SuperWetExtensionTimeMicroseconds /t REG_DWORD /d 1000 /f
reg add "%DwmKey%" /v TelemetryFramesReportPeriodMilliseconds /t REG_DWORD /d 300000 /f
reg add "%DwmKey%" /v TelemetryFramesSequenceIdleIntervalMilliseconds /t REG_DWORD /d 1000 /f
reg add "%DwmKey%" /v TelemetryFramesSequenceMaximumPeriodMilliseconds /t REG_DWORD /d 1000 /f
reg add "%DwmKey%" /v UniformSpaceDpiMode /t REG_DWORD /d 1 /f
reg add "%DwmKey%" /v UseFastestMonitorAsPrimary /t REG_DWORD /d 0 /f
reg add "%DwmKey%" /v vBlankWaitTimeoutMonitorOffMs /t REG_DWORD /d 250 /f
reg add "%DwmKey%" /v WarpEnableDebugColor /t REG_DWORD /d 0 /f
reg add "%DwmKey%" /v BackdropBlurCachingThrottleMs /t REG_DWORD /d 25 /f
reg add "%DwmKey%" /v CompositorClockPolicy /t REG_DWORD /d 1 /f
reg add "%DwmKey%" /v CpuClipFlatteningTolerance /t REG_DWORD /d 0 /f
reg add "%DwmKey%" /v CustomRefreshRateMode /t REG_DWORD /d 0 /f
reg add "%DwmKey%" /v DisableAdvancedDirectFlip /t REG_DWORD /d 0 /f
reg add "%DwmKey%" /v DisableIndependentFlip /t REG_DWORD /d 0 /f
reg add "%DwmKey%" /v DisableProjectedShadowsRendering /t REG_DWORD /d 0 /f
reg add "%DwmKey%" /v FlattenVirtualSurfaceEffectInput /t REG_DWORD /d 0 /f
reg add "%DwmKey%" /v ForceEffectMode /t REG_DWORD /d 0 /f
reg add "%DwmKey%" /v FrameCounterPosition /t REG_DWORD /d 0 /f
reg add "%DwmKey%" /v InteractionOutputPredictionDisabled /t REG_DWORD /d 0 /f
reg add "%DwmKey%" /v OverlayTestMode /t REG_DWORD /d 5 /f
reg add "%DwmKey%" /v ParallelModePolicy /t REG_DWORD /d 1 /f
reg add "%DwmKey%" /v ParallelModeRateThreshold /t REG_DWORD /d 144 /f
reg add "%DwmKey%" /v ResampleInLinearSpace /t REG_DWORD /d 0 /f
reg add "%DwmKey%" /v ResampleModeOverride /t REG_DWORD /d 0 /f
reg add "%DwmKey%" /v SDRBoostPercentOverride /t REG_DWORD /d 0 /f
reg add "%DwmKey%" /v ShowDirtyRegions /t REG_DWORD /d 0 /f
reg add "%DwmKey%" /v AnimationsShiftKey /t REG_DWORD /d 0 /f
reg add "%DwmKey%" /v DisableLockingMemory /t REG_DWORD /d 0 /f
reg add "%DwmKey%" /v ModeChangeCurtainUseDebugColor /t REG_DWORD /d 0 /f
reg add "%DwmKey%" /v UseDPIScaling /t REG_DWORD /d 1 /f
reg add "%DwmKey%" /v ChildWindowDpiIsolation /t REG_DWORD /d 1 /f
reg add "%DwmKey%" /v DisableDeviceBitmaps /t REG_DWORD /d 0 /f
reg add "%DwmKey%" /v EnableResizeOptimization /t REG_DWORD /d 0 /f
reg add "%DwmKey%" /v ResizeTimeoutGdi /t REG_DWORD /d 0 /f
reg add "%DwmKey%" /v ResizeTimeoutModern /t REG_DWORD /d 0 /f
reg add "%DwmKey%" /v DefaultColorizationColorState /t REG_DWORD /d 0 /f
reg add "%DwmKey%" /v DisallowAnimations /t REG_DWORD /d 0 /f
reg add "%DwmKey%" /v DisallowColorizationColorChanges /t REG_DWORD /d 0 /f
reg add "%DwmKey%" /v DisableSessionTermination /t REG_DWORD /d 0 /f
reg add "%DwmKey%" /v ForceBasicDisplayAdapterOnDWMRestart /t REG_DWORD /d 0 /f
reg add "%DwmKey%" /v OneCoreNoBootDWM /t REG_DWORD /d 0 /f
reg add "%DwmKey%" /v DisableHologramCompositor /t REG_DWORD /d 0 /f
reg add "%DwmKey%" /v OverrideMonitorRefreshRate /t REG_DWORD /d 0 /f
reg add "%DwmKey%" /v Disable_MPO /t REG_DWORD /d 0 /f
set "DwmSceneKey=%DwmKey%\Scene"
reg add "%DwmSceneKey%" /v EnableBloom /t REG_DWORD /d 0 /f
reg add "%DwmSceneKey%" /v EnableDrawToBackbuffer /t REG_DWORD /d 1 /f
reg add "%DwmSceneKey%" /v EnableImageProcessing /t REG_DWORD /d 1 /f
reg add "%DwmSceneKey%" /v ImageProcessingResizeGrowth /t REG_DWORD /d 200 /f
reg add "%DwmSceneKey%" /v MsaaQualityMode /t REG_DWORD /d 2 /f
reg add "%DwmSceneKey%" /v SceneVisualCutoffCountOfConsecutiveIncidentsAllowed /t REG_DWORD /d 5 /f
reg add "%DwmSceneKey%" /v SceneVisualCutoffThresholdInMS /t REG_DWORD /d 1000 /f
reg add "%DwmSceneKey%" /v ForceNonPrimaryDisplayAdapter /t REG_DWORD /d 0 /f
reg add "%DwmSceneKey%" /v ImageProcessingResizeThreshold /t REG_DWORD /d 0 /f
set "DwmInkKey=%DwmKey%\GpuAccelInkTiming"
reg add "%DwmInkKey%" /v ExtensionTimeMicroseconds /t REG_DWORD /d 1000 /f
reg add "%DwmInkKey%" /v PeriodicFenceMinDifferenceMicroseconds /t REG_DWORD /d 500 /f
reg add "%DwmInkKey%" /v RefreshRatePercentage /t REG_DWORD /d 10 /f
:: GPU Priority tweaks for gaming
reg add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile\Tasks\Games" /v "GPU Priority" /t REG_DWORD /d 8 /f
reg add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile\Tasks\Games" /v "Priority" /t REG_DWORD /d 6 /f
reg add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile\Tasks\Games" /v "Scheduling Category" /t REG_SZ /d "High" /f
reg add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile\Tasks\Games" /v "SFIO Priority" /t REG_SZ /d "High" /f
endlocal